### ISSUE TITLE
Iterate on `Codec`

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/calico#138]
https://github.com/armanbilge/calico/blob/642b1b8ec119f3849b9566644024f82aa2737a53/calico/src/main/scala/calico/html/codecs/Codec.scala#L30

- error handling for failed decoding
- flatten package structure
- reduce footprint (?)

**Comment by 2chilled** [comment]
> error handling for failed decoding

I think these `Double` and `Int` impls shouldn't exist. Just replace them by `Option[Double]` and `Option[Int]`? The other ones look ok.

> flatten package structure

Do you want to put this into html.scala as well?

> reduce footprint (?)

What do you mean by this, footprint of the Scala Code or of the resulting JS?

**Comment by 2chilled** [comment]
> You think this is better than using Either for decode

If we've already seen all instances there is, then I think yes. That'd mean the majority of them doesn't need to express failure/non existence at all. 

> to clarify, I think it should go in the html package

:+1: 

> reduce API footprint
> reduce JS footprint

Thanks for clarifying :+1:
