### ISSUE TITLE
An easy way to "amend" an already constructed element

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/calico#204]
We could probably support `div(...).flatTap(_.modify(...))` fairly easily. Anything more would require adding syntax to `Resource[IO, HtmlElement]` which I am not crazy about.

**Comment by hejfelix** [comment]
You are on a roll with these issues. Most of it is stuff I have been halfway through posting – bless you! 🙏

**Comment by armanbilge** [comment]
- https://github.com/armanbilge/calico/pull/222
