### ISSUE TITLE
`-->` alternatives / overloads

### ISSUE THREAD

**Issue by kubukoz** [armanbilge/calico#400]
I think the following pattern:

```scala
foo --> (_.foreach(_ => f))
```

is so common that it'd be worth supporting as a first-class thing, especially given `_.foreach` needs parens because of precedence rules. How about:

```scala
// takes F[Unit]
foo.each(f)
// takes Event[F] => F[Unit]
foo.foreach(_ => f)
```

**Comment by armanbilge** [comment]
thoughts about?
- https://github.com/armanbilge/calico/pull/223

**Comment by kubukoz** [comment]
I like it, maybe not the particular choice of operator though... and definitely agree that creating new fibers by default isn't the way to go.

I wonder if we could frame this is as an arrow composition problem, with some implicit conversions for the RHS so that it can be either a pipe, an effectful function or just an effect. Still, implicit conversions for functions/pipes won't be any good for type inference.

**Comment by armanbilge** [comment]
> ```scala
> foo --> (_.foreach(_ => f))
> ```

So actually it's usually not `foo` but `onFoo` ... what if we did something like `onFoo.do(f)` or even just `onFoo(f)`.

**Comment by armanbilge** [comment]
> Oh, and sorry for duplicating #202.

Oh lol forgot that 😆

**Comment by kubukoz** [comment]
> > ```scala
> > foo --> (_.foreach(_ => f))
> > ```
> 
> So actually it's usually not `foo` but `onFoo` ... what if we did something like `onFoo.do(f)` or even just `onFoo(f)`.

`onFoo(f)` looks great :)
